services:
  app:
    build: ./app
    container_name: quest15-app
    hostname: ip-10-0-1-42
    privileged: true
    cgroup: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - private-subnet
    ports:
      - "2227:22"
    depends_on:
      - db

  # DBインスタンス。ポートは外に出していない。SSHも無い
  db:
    build: ./db
    container_name: quest15-db
    hostname: ip-10-0-101-7
    networks:
      private-subnet:
        aliases:
          - reportdb.internal

networks:
  private-subnet:
