services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      # わざと間違ったサービス名を指すように設定してある(意図的な設定ミス)
      DB_HOST: "db-server"
    depends_on:
      - db

  db:
    build: ./db
